---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-secret-config
  namespace: flux-system
data:
  # Patch this ConfigMap with additional values needed for your cloud
  KUBE_SECRET: my-secret # does not yet exist -- will be created in the same Namespace
  SYNC_PERIOD: "3600" # tokens expire; refresh faster than that
  ADO_RESOURCE_ID: "499b84ac-1321-427f-aa17-267ca6975798"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sync-secret
  name: sync-secret
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-secret
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sync-secret
        aadpodidbinding: flux-source-controller
    spec:
      serviceAccount: source-controller
      serviceAccountName: source-controller
      containers:
        - image: mcr.microsoft.com/azure-cli
          name: sync-secret
          envFrom:
            - configMapRef:
                name: sync-secret-config
          command: ["/bin/sh"]
          args:
            - "-ceu" # -c: exit on error; -e: exit on unset var; -u: exit on unset var in subshell
            - |-

              # Install kubectl
              apk --no-cache add curl
              curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              mv ./kubectl /usr/local/bin

              reconcile() {
                echo "Updating secret: $KUBE_SECRET -- $(date)"
                
                echo "Logging to Azure with managed identity..."
                az login --identity
                echo "Getting ADO token..."
                token=$(az account get-access-token --resource "$ADO_RESOURCE_ID" --query "accessToken" --output tsv)
                echo "Done!"
                
                applySecret "$KUBE_SECRET" "git" "$token"
                echo "Finished! -- $(date)"
              }

              applySecret() {
                kubectl create secret generic "$1" \
                  --from-literal=username="$2" \
                  --from-literal=password="$3" \
                  --dry-run=client \
                  --output yaml \
                  | grep -v "creationTimestamp:" \
                  | kubectl apply -f -
              }

              pause_loop() {
                sleep "$SYNC_PERIOD" || true
              }

              graceful_exit() {
                echo "Trapped signal -- $(date)"
                job_ids="$(
                  jobs \
                    | grep "pause_loop" \
                    | cut -d] -f1 \
                    | tr [ %
                  )"
                # shellcheck disable=SC2086
                if [ "$job_ids" ]; then
                  kill $job_ids
                fi
                wait
                echo "Graceful exit -- $(date)"
              }

              trap graceful_exit INT TERM

              echo "Loop started (period: $SYNC_PERIOD s) -- $(date)"
              while true; do
                reconcile & wait $!
                pause_loop & wait $!
              done
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "50m"
