apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - roles.yml
  - deployment.yml
configMapGenerator:
  - name: sync-secret-config
    behavior: merge
    namespace: flux-system
    literals:
      - KUBE_SECRET=my-secret
      - SYNC_PERIOD=3600
