---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-creator-role
  namespace: secret-sync
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-creator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-creator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: secret-sync