---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-identity-token-sync
  namespace: flux-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - secret/my-secret
    verbs:
      - get
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-identity-token-sync-binding
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-identity-token-sync
subjects:
  - kind: ServiceAccount
    name: source-controller
    namespace: flux-system
